fixed many warnings from shellcheck

diff --git a/autocalibration/src/camcalibration-init b/autocalibration/src/camcalibration-init
--- a/autocalibration/src/camcalibration-init
+++ b/autocalibration/src/camcalibration-init
@@ -20,8 +20,10 @@ map_dir() {
     local DUID=$3
     local DGID=$4
 
-    local SUID=$(stat -c '%u' "${SRC}")
-    local SGID=$(stat -c '%g' "${SRC}")
+    local SUID
+    SUID=$(stat -c '%u' "${SRC}")
+    local SGID
+    SGID=$(stat -c '%g' "${SRC}")
 
     mkdir -p "${DEST}"
     chown "${DUID}:${DGID}" "${DEST}"
@@ -52,12 +54,12 @@ if [ -d "${WORKSPACE}" ]; then
     if [ -n "${HOSTDIR}" ]; then
         mkdir -p "${HOSTDIR}"
         mount --bind "${WORKSPACE}" "${HOSTDIR}"
-        cd "${HOSTDIR}"
+        cd "${HOSTDIR}" || { echo "Failed to change directory to ${HOSTDIR}"; exit 1; }
     else
-        cd "${WORKSPACE}"
+        cd "${WORKSPACE}" || { echo "Failed to change directory to ${WORKSPACE}"; exit 1; }
     fi
 else
-    cd "${SSCAPEDIR}"
+    cd "${SSCAPEDIR}" || { echo "Failed to change directory to ${SSCAPEDIR}"; exit 1; }
 fi
 
 if [ -n "${SECRETSDIR}" ] ; then
@@ -78,7 +80,7 @@ case "${DBROOT}" in
     *) DBROOT=${WORKSPACE}/${DBROOT} ;;
 esac
 
-while [ $# -gt 0 -a x$(expr substr "$1" 1 2) = "x--" ] ; do
+while [ $# -gt 0 ] && [ "x$(expr substr $1 1 2)" = "x--" ] ; do
     case "$1" in
         --shell)
             DO_SHELL=user
@@ -103,7 +105,7 @@ if [ "$1" = "camcalibration" ] || [ "$1" = "server" ]; then
     shift
 fi
 
-while [ $# -gt 0 -a x$(expr substr "${1:-empty}" 1 2) = "x--" ] ; do
+while [ $# -gt 0 ] && [ "x$(expr substr ${1:-empty} 1 2)" = "x--" ] ; do
     case "$1" in
         --broker)
             BROKER="$1 $2"
@@ -153,16 +155,16 @@ if [ -n "${WAITPID}" ]; then
 else
     if [ "${DO_SHELL}" = 'user' ] ; then
         if [ $# -gt 0 ] ; then
-            echo "Starting shell with command: $@"
+            echo "Starting shell with command:" "$@"
             IFS=
-            sudo -u ${WSUSER} -E -H -s $@
+            sudo -u ${WSUSER} -E -H -s "$@"
         else
             echo "Starting shell"
             su ${WSUSER}
         fi
     elif [ "${DO_SHELL}" = 'super' ] ; then
         if [ $# -gt 0 ] ; then
-            echo "Starting super shell with command: $@"
+            echo "Starting super shell with command:" "$@"
             /bin/bash -c "$@"
         else
             echo "Starting super shell"
@@ -171,7 +173,7 @@ else
     else
         if [ $# -gt 0 ] ; then
             IFS=
-            sudo -u ${WSUSER} -E -H $@
+            sudo -u ${WSUSER} -E -H "$@"
         else
             su ${WSUSER}
         fi
diff --git a/manager/config/database-init b/manager/config/database-init
--- a/manager/config/database-init
+++ b/manager/config/database-init
@@ -49,7 +49,7 @@ fi
 /etc/init.d/postgresql start
 COUNT=0
 PIDFILE=/run/postgresql/${PSQLVER}-main.pid
-while [ ! -e ${PIDFILE} -a ${COUNT} -lt 5 ] ; do
+while [ ! -e ${PIDFILE} ] && [ ${COUNT} -lt 5 ] ; do
     COUNT=$(expr ${COUNT} + 1)
     echo Postgres not started yet: ${COUNT}
     sleep 1
@@ -60,7 +60,7 @@ if [ ! -e ${PIDFILE} ] ; then
 fi
 WAITPID="${WAITPID} $(cat ${PIDFILE})"
 
-cd ${MANAGERDIR}
+cd ${MANAGERDIR} || { echo "Failed to change directory to ${MANAGERDIR}"; exit 1; }
 
 if [ ${CREATEDB} = 1 ] ; then
     echo ''
@@ -118,7 +118,7 @@ if [ ${CREATEDB} = 1 ] ; then
     elif [ -e ${MANAGERDIR}/${EXAMPLEDB} ] ; then
         EXAMPLEDB=${MANAGERDIR}/${EXAMPLEDB}
     fi
-    if [ ${PRELOAD} = 1 -a -e ${EXAMPLEDB} ] ; then
+    if [ ${PRELOAD} = 1 ] && [ -e ${EXAMPLEDB} ] ; then
         echo ''
         echo '#############'
         echo "Preloading example"
@@ -143,7 +143,7 @@ PORT=${HOSTPORT[1]}
 fi
 BROKERROOTCERT=${BROKERROOTCERT:-${RUNSECRETS}/scenescape-ca.pem}
 BROKERAUTH=${BROKERAUTH:-${RUNSECRETS}/controller.auth}
-if [ -e ${BROKERAUTH} -a -e ${BROKERROOTCERT} ] ; then
+if [ -e ${BROKERAUTH} ] && [ -e ${BROKERROOTCERT} ] ; then
     AUTH=($(python3 -c "import sys, json; auth=json.load(sys.stdin); print(auth['user'], auth['password'])" < ${BROKERAUTH}))
     mosquitto_pub --tls-version tlsv1.3 --cafile ${BROKERROOTCERT} -h ${HOST} -p ${PORT} \
                 -u ${AUTH[0]} -P ${AUTH[1]} -t scenescape/cmd/database -m "update" &
diff --git a/percebro/src/percebro-init b/percebro/src/percebro-init
--- a/percebro/src/percebro-init
+++ b/percebro/src/percebro-init
@@ -24,10 +24,10 @@ if [ -d "${WORKSPACE}" ] ; then
         exit 1
     fi
     chown ${WSUID}:${WSGID} ${WORKSPACE}
-    if [ ${WSGID} != $(id -g ${WSUSER}) ] ; then
+    if [ ${WSGID} != "$(id -g ${WSUSER})" ] ; then
         groupmod -g ${WSGID} ${WSUSER}
     fi
-    if [ ${WSGID} != $(id -g ${WSUSER}) -o ${WSUID} != $(id -u ${WSUSER}) ] ; then
+    if [ ${WSGID} != "$(id -g ${WSUSER})" ] || [ ${WSUID} != "$(id -u ${WSUSER})" ] ; then
         usermod -u ${WSUID} -g ${WSGID} ${WSUSER}
     fi
 
@@ -35,12 +35,12 @@ if [ -d "${WORKSPACE}" ] ; then
     if [ -n "${HOSTDIR}" ] ; then
         mkdir -p "${HOSTDIR}"
         mount --bind "${WORKSPACE}" "${HOSTDIR}"
-        cd "${HOSTDIR}"
+        cd "${HOSTDIR}" || { echo "Failed to change directory to ${HOSTDIR}"; exit 1; }
     else
-        cd "${WORKSPACE}"
+        cd "${WORKSPACE}" || { echo "Failed to change directory to ${WORKSPACE}"; exit 1; }
     fi
 else
-    cd "${SSCAPEDIR}"
+    cd "${SSCAPEDIR}" || { echo "Failed to change directory to ${SSCAPEDIR}"; exit 1; }
 fi
 
 if [ -n "${SECRETSDIR}" ] ; then
@@ -55,7 +55,7 @@ if [ ! -e ${RUNSECRETS} ] && [ -n "${SECRETSDIR}" ] && [ -d "${SECRETSDIR}" ] ; 
     ln -s ${SECRETSDIR} ${RUNSECRETS}
 fi
 
-while [ $# -gt 0 -a x$(expr substr "$1" 1 2) = "x--" ] ; do
+while [ $# -gt 0 ] && [ "x$(expr substr $1 1 2)" = "x--" ] ; do
     case "$1" in
         --shell)
             DO_SHELL=user
@@ -78,7 +78,7 @@ if [ "$1" = "percebro" ]; then
     shift
 fi
 
-while [ $# -gt 0 -a x$(expr substr "${1:-empty}" 1 2) = "x--" ] ; do
+while [ $# -gt 0 ] && [ "x$(expr substr ${1:-empty} 1 2)" = "x--" ] ; do
     case "$1" in
         --broker)
             BROKER="$1 $2"
@@ -122,16 +122,16 @@ if [ -n "${WAITPID}" ]; then
 else
     if [ "${DO_SHELL}" = 'user' ] ; then
         if [ $# -gt 0 ] ; then
-            echo "Starting shell with command: $@"
+            echo "Starting shell with command:" "$@"
             IFS=
-            sudo -u ${WSUSER} -E -H -s $@
+            sudo -u ${WSUSER} -E -H -s "$@"
         else
             echo "Starting shell"
             su ${WSUSER}
         fi
     elif [ "${DO_SHELL}" = 'super' ] ; then
         if [ $# -gt 0 ] ; then
-            echo "Starting super shell with command: $@"
+            echo "Starting super shell with command:" "$@"
             /bin/bash -c "$@"
         else
             echo "Starting super shell"
@@ -140,7 +140,7 @@ else
     else
         if [ $# -gt 0 ] ; then
             IFS=
-            sudo -u ${WSUSER} -E -H $@
+            sudo -u ${WSUSER} -E -H "$@"
         else
             su ${WSUSER}
         fi
